const plants = [
  {name:"Aloe Vera", water:2, light:4, temp:22, tip:"Keep in bright, indirect light. Water when soil dry."},
  {name:"Spider Plant", water:3, light:3, temp:21, tip:"Prefers moderate light. Avoid overwatering."},
  {name:"Peace Lily", water:4, light:2, temp:24, tip:"Low light okay. Keep soil moist."},
  {name:"Snake Plant", water:1, light:3, temp:23, tip:"Can survive low light. Let soil dry completely between waterings."},
  {name:"Pothos", water:3, light:3, temp:22, tip:"Tolerates low light. Water when top inch dry."},
  {name:"Fiddle Leaf Fig", water:2, light:5, temp:25, tip:"Needs bright light. Water when soil dry."},
  {name:"Rubber Plant", water:2, light:4, temp:23, tip:"Bright indirect light. Moderate watering."},
  {name:"Dracaena", water:2, light:3, temp:22, tip:"Tolerates low light. Keep soil slightly moist."},
  {name:"ZZ Plant", water:1, light:2, temp:22, tip:"Low light. Very drought tolerant."},
  {name:"Boston Fern", water:4, light:3, temp:20, tip:"Likes humidity. Keep soil moist."},
  {name:"Jade Plant", water:1, light:5, temp:23, tip:"Needs bright light. Allow soil to dry between waterings."},
  {name:"Begonia", water:3, light:3, temp:21, tip:"Indirect light. Keep soil moist but not soggy."},
  {name:"African Violet", water:3, light:3, temp:22, tip:"Bright indirect light. Water from bottom."},
  {name:"Orchid", water:2, light:4, temp:24, tip:"Bright indirect light. Water weekly."},
  {name:"Calathea", water:4, light:2, temp:22, tip:"Low light. Keep soil consistently moist."},
  {name:"Philodendron", water:3, light:3, temp:22, tip:"Moderate light. Let topsoil dry slightly between waterings."},
  {name:"Monstera", water:3, light:4, temp:22, tip:"Bright indirect light. Water moderately."},
  {name:"Bromeliad", water:2, light:3, temp:23, tip:"Indirect light. Keep center cup filled with water."},
  {name:"Cactus", water:1, light:5, temp:25, tip:"Bright light. Water sparingly."},
  {name:"Lavender", water:2, light:5, temp:24, tip:"Needs full sun. Water when dry."},
  {name:"Mint", water:4, light:3, temp:22, tip:"Indirect light. Keep soil moist."},
  {name:"Rosemary", water:2, light:5, temp:23, tip:"Bright sun. Water when soil dry."},
  {name:"Basil", water:3, light:4, temp:22, tip:"Bright indirect light. Keep soil moist."},
  {name:"Thyme", water:2, light:5, temp:23, tip:"Needs bright light. Allow soil to dry."},
  {name:"Parsley", water:3, light:4, temp:22, tip:"Moderate light. Keep soil moist."},
  {name:"Chives", water:3, light:4, temp:21, tip:"Moderate light. Water regularly."},
  {name:"Sage", water:2, light:5, temp:23, tip:"Full sun. Let soil dry between waterings."},
  {name:"Oregano", water:2, light:5, temp:22, tip:"Bright sun. Water moderately."},
  {name:"Lemon Balm", water:3, light:3, temp:22, tip:"Indirect light. Keep soil moist."},
  {name:"Cilantro", water:3, light:4, temp:22, tip:"Bright indirect light. Keep soil moist."},
  {name:"Echeveria", water:1, light:5, temp:24, tip:"Bright light. Water sparingly."},
  {name:"Hoya", water:2, light:4, temp:22, tip:"Bright indirect light. Let soil dry between waterings."},
  {name:"Kalanchoe", water:2, light:4, temp:23, tip:"Bright light. Water moderately."},
  {name:"Pilea", water:3, light:3, temp:22, tip:"Indirect light. Water when topsoil dry."},
  {name:"Peperomia", water:2, light:3, temp:22, tip:"Low to medium light. Let soil dry slightly."},
  {name:"Schefflera", water:3, light:4, temp:22, tip:"Bright indirect light. Water moderately."},
  {name:"Ficus", water:3, light:4, temp:22, tip:"Bright indirect light. Keep soil evenly moist."},
  {name:"Anthurium", water:3, light:3, temp:23, tip:"Low to medium light. Keep soil moist."},
  {name:"Begonia Rex", water:3, light:3, temp:22, tip:"Bright indirect light. Keep soil moist."},
  {name:"Maranta", water:4, light:2, temp:22, tip:"Low light. Keep soil consistently moist."},
  {name:"Dracaena Marginata", water:2, light:3, temp:22, tip:"Moderate light. Water when soil dry."},
  {name:"Fatsia Japonica", water:3, light:3, temp:21, tip:"Indirect light. Keep soil moist."},
  {name:"Cyclamen", water:3, light:3, temp:20, tip:"Indirect light. Water from bottom to avoid crown rot."},
  {name:"Hibiscus", water:4, light:4, temp:24, tip:"Bright light. Keep soil consistently moist."},
  {name:"Gardenia", water:4, light:4, temp:23, tip:"Bright indirect light. Keep soil moist."},
  {name:"Bougainvillea", water:2, light:5, temp:24, tip:"Full sun. Allow soil to dry between waterings."},
  {name:"Hydrangea", water:4, light:3, temp:22, tip:"Bright indirect light. Keep soil moist."}
];
