const plants = [
  { name: "Snake Plant", water: 0, light: 1, temp: 20, tip: "Very hardy, water sparingly. Low light friendly." },
  { name: "Pothos", water: 1, light: 1, temp: 22, tip: "Thrives in most conditions. Trim leaves occasionally." },
  { name: "Spider Plant", water: 1, light: 2, temp: 22, tip: "Avoid direct sun. Great for hanging baskets." },
  { name: "ZZ Plant", water: 0, light: 1, temp: 20, tip: "Tolerates neglect. Avoid overwatering." },
  { name: "Fiddle Leaf Fig", water: 2, light: 2, temp: 24, tip: "Needs bright indirect light. Rotate regularly." },
  { name: "Rubber Plant", water: 1, light: 2, temp: 22, tip: "Can handle low light. Wipe leaves occasionally." },
  { name: "Peace Lily", water: 2, light: 1, temp: 22, tip: "Prefers medium light. Flowers in low light." },
  { name: "Monstera Deliciosa", water: 1, light: 2, temp: 22, tip: "Likes bright indirect light. Support stems as it grows." },
  { name: "Dracaena", water: 1, light: 1, temp: 21, tip: "Avoid overwatering. Thrives in low light." },
  { name: "Calathea", water: 2, light: 1, temp: 22, tip: "Keep soil moist. Sensitive to direct sun." },
  { name: "Aloe Vera", water: 0, light: 2, temp: 23, tip: "Needs bright light. Let soil dry between watering." },
  { name: "Cactus", water: 0, light: 3, temp: 28, tip: "Water rarely. Loves sun." },
  { name: "Boston Fern", water: 2, light: 1, temp: 20, tip: "Keep soil moist. Prefers indirect light." },
  { name: "Chinese Evergreen", water: 1, light: 1, temp: 22, tip: "Low maintenance. Avoid direct sun." },
  { name: "Neon Pothos", water: 1, light: 2, temp: 22, tip: "Bright indirect light improves leaf color." },
  { name: "Hoya", water: 1, light: 2, temp: 23, tip: "Likes bright light. Let soil dry between watering." },
  { name: "African Violet", water: 2, light: 2, temp: 21, tip: "Keep soil moist. Avoid wetting leaves." },
  { name: "Croton", water: 2, light: 2, temp: 24, tip: "Needs bright light to keep leaf colors vivid." },
  { name: "Prayer Plant", water: 2, light: 1, temp: 22, tip: "Keep soil consistently moist. Low light tolerant." },
  { name: "Kalanchoe", water: 0, light: 2, temp: 23, tip: "Let soil dry between watering. Needs bright light." },
  { name: "Ponytail Palm", water: 0, light: 2, temp: 25, tip: "Store water in bulb. Bright light preferred." },
  { name: "String of Pearls", water: 0, light: 2, temp: 23, tip: "Water sparingly. Likes bright indirect light." },
  { name: "Cast Iron Plant", water: 1, light: 1, temp: 21, tip: "Extremely hardy. Low maintenance." },
  { name: "Corn Plant", water: 1, light: 1, temp: 22, tip: "Avoid direct sunlight. Moderate watering." },
  { name: "Arrowhead Plant", water: 1, light: 2, temp: 22, tip: "Bright indirect light. Keep soil slightly moist." },
  { name: "Silver Pothos", water: 1, light: 1, temp: 22, tip: "Low light tolerant. Water moderately." },
  { name: "Bamboo Palm", water: 1, light: 1, temp: 21, tip: "Prefers low light. Keep soil evenly moist." },
  { name: "Fittonia", water: 2, light: 1, temp: 22, tip: "Keep soil moist. Sensitive to dryness." },
  { name: "Anthurium", water: 2, light: 2, temp: 23, tip: "Needs bright indirect light. Water regularly." },
  { name: "Philodendron", water: 1, light: 1, temp: 22, tip: "Tolerates low light. Moderate watering." },
  { name: "Areca Palm", water: 1, light: 2, temp: 23, tip: "Likes bright light. Water consistently." },
  { name: "Chinese Money Plant", water: 1, light: 1, temp: 22, tip: "Easy to grow. Avoid overwatering." },
  { name: "Dragon Tree", water: 1, light: 1, temp: 21, tip: "Low maintenance. Moderate watering." },
  { name: "Silver Queen Aglaonema", water: 1, light: 1, temp: 21, tip: "Thrives in low light. Keep soil moist." },
  { name: "Jade Plant", water: 0, light: 2, temp: 24, tip: "Water sparingly. Needs bright light." },
  { name: "Bird of Paradise", water: 2, light: 2, temp: 25, tip: "Needs bright light. Water regularly." },
  { name: "Philodendron Brasil", water: 1, light: 1, temp: 22, tip: "Low maintenance. Moderate watering." },
  { name: "Peace Lily Dwarf", water: 2, light: 1, temp: 22, tip: "Medium light preferred. Keep soil moist." },
  { name: "Yucca", water: 0, light: 2, temp: 24, tip: "Water sparingly. Likes bright light." },
  { name: "Nerve Plant", water: 2, light: 1, temp: 22, tip: "Keep soil moist. Low light tolerant." },
  { name: "Begonia", water: 2, light: 2, temp: 23, tip: "Prefers bright indirect light. Keep soil moist." },
  { name: "English Ivy", water: 1, light: 1, temp: 22, tip: "Moderate light. Keep soil evenly moist." },
  { name: "Aluminum Plant", water: 1, light: 1, temp: 21, tip: "Low light tolerant. Water moderately." },
  { name: "Christmas Cactus", water: 0, light: 2, temp: 22, tip: "Water sparingly. Likes indirect light." },
  { name: "Pink Quill Plant", water: 2, light: 2, temp: 23, tip: "Bright indirect light. Keep soil moist." },
  { name: "Fishbone Cactus", water: 0, light: 2, temp: 24, tip: "Water sparingly. Bright light preferred." },
  { name: "Pilea Peperomioides", water: 1, light: 2, temp: 22, tip: "Moderate light. Let soil dry slightly between waterings." }
];
